---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

Here, we're just setting a few options.

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```

Now, we're preparing our data for the codebook.

```{r prepare_codebook}
#load packages
    library(codebook)
    library(labelled)
    library(dplyr)  #To reshape the imported dict df into a list
#Data : Import
    source("./scripts/extractMergeCreateDf.R")
    codebook_data <- mergedDf; rm(mergedDf)

#Metadata : Add
    metadata(codebook_data)$name <- "Human Activity Recognition Using Smartphones Dataset"

    metadata(codebook_data)$description <- "The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist."
  
    metadata(codebook_data)$creator <- "Emmanuel Clivaz"
    metadata(codebook_data)$citation <- "Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto. Smartlab - Non Linear Complex Systems Laboratory. DITEN - Università degli Studi di Genova."

    metadata(codebook_data)$url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
    metadata(codebook_data)$datePublished <- "2013-04-24"
    metadata(codebook_data)$temporalCoverage <- "Spring 2013"
    metadata(codebook_data)$spatialCoverage <- "Online"

#Labels : Variables
    # Dict : Import
    dict <- labelMergedDf; rm(labelMergedDf)
    
     #df expected => 2 col df : 1st col var name, 2nd col var labels / use dplyr
    var_label(codebook_data) <- dict %>%
        select(variable, label) %>%
        dict_to_list()  # will make a list to be used as label which requires list format
    
#Labels : Values
    labVal <- read.table("./data/sourceData/activity_labels.txt", header = FALSE) %>%
        pull(V2) %>%
        as.character() %>%
        tolower()
            
    labVal <- sub("_", " ", labVal)
              
    codebook_data$labels <- factor(codebook_data$labels, levels = c(1,2,3,4,5,6), labels= labVal)
    
    codebook_data$set <- factor(codebook_data$set, levels = c(1,2), labels = c("train", "test"))
    rm(labVal)
    
    
    
    
#Export/share data with metadata (use the rio package for export)
        #Only way to keep all metadata in one file:
    rio::export(codebook_data, "./data/finalData/metadataFile.rds") # means to R data structure file

    
    

# Labels
    # Missing values
    codebook_data <- detect_missing(codebook_data,only_labelled = TRUE, # only labelled values are autodetected as missing - > yes
    negative_values_are_missing = FALSE, # negative values are missing values -> no
    ninety_nine_problems = FALSE,   # 99/999 are missing values, if they are more than 5 MAD from the median -> no
    )

# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
codebook_data <- detect_scales(codebook_data)



# need to save codebook_data into the file data


```


Create codebook

```{r codebook}
codebook(codebook_data)
```
